run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/miss-you/codetok
  misspell:
    locale: US

issues:
  exclude-use-default: true
